### ISSUE TITLE
이미지 분류 api 요청 시 대기 시간 예측 불가로 버퍼링 딜레이를 맞출 수 없음

### ISSUE THREAD

**Issue by pch121** [723poil/moapp_1#11]
api 요청 시 약 5초 동안 대기를 해야 하는데 버퍼링 딜레이를 주고 언제 멈춰야 할지 잘 모르겠음

**Comment by 723poil** [comment]
코루틴과 오브젝트 클래스를 사용해서 오브젝트의 변수값이 변하면 api 요청 결과값을 받은것으로 간주하고 버퍼링을 종료하도록 유도함
